### ISSUE TITLE
support for config files?

### ISSUE THREAD

**Issue by pchalasani** [AshwinParanjape/meticulous-ml#4]
Thanks for the interesting exp-tracking package. 

Your solution seems to be centered on `argparse` and command-line based flags. 
I generally set up many params in a `yaml` config file (and I suspect many others do it this way),
and I use a package like [`parse_it`](https://github.com/naorlivne/parse_it) to override them at the command line, without having to specify an `argparse` line for each of those args. However the end-result of using `ParseIt` is a simple config dictionary, not an argparse object.

Any ideas on how I can adapt meticulous seems to work with an arbitrary dictionary of params?

**Comment by pchalasani** [comment]
actually I see this is possible, in the advanced options.

**Comment by AshwinParanjape** [comment]
That is correct, you can simply pass in an arbitrary dictionary of params as the first argument to Experiment object constructor. 

Putting up a link to the relevant section of the docs - https://ashwinparanjape.github.io/meticulous-ml/advanced_tracking.html#using-a-config-file-instead-of-argparse

Hope you are finding the package useful thus far :)

**Comment by pchalasani** [comment]
The one thing I found problematic for my purposes is the restriction that I have to have clean committed git state in order to use this. I often make trivial changes to "try things out", and it creates a messy git history to keep committing those. I'm looking at the `replicate`  project for ml version control and so far it looks promising.

**Comment by AshwinParanjape** [comment]
Yup, being able to skip checks during development is very much necessary. I use `--norecord` option (documentation - https://ashwinparanjape.github.io/meticulous-ml/advanced_tracking.html#skipping-checks-during-development) while I'm "trying things out" but then as soon as I'm ready to record the experiments, I commit and run without the `--norecord` option.  It might be useful for you. 

I hadn't heard of replicate, but that looks good too 👍 It seems like they are doing version control but without using git which seems quite interesting.

**Comment by pchalasani** [comment]
I actually want to be able to record experiments without having to do a git commit, even when I’m just “trying things out”. Replicate allows this. But their logging is restricted to model checkpoints during training.
